### ISSUE TITLE
task-mate-minimal is missing

### ISSUE THREAD

**Issue by CasualRascal** [OpenMandrivaAssociation/task-mate#2]
task-mate-minimal package is missing, somehow? Can't find it on abf and you tried to build task-mate this week and the build failed because it is missing.

The task-mate-minimal I have cached lacks networkmanager-applet. Add networkmanager-applet to required or users will be unable to connect to wifi using the gui.

**Comment by AngryPenguinPL** [comment]
> task-mate-minimal package is missing, somehow? Can't find it on abf and you tried to build task-mate this week and the build failed because it is missing.

Huh? Is not missing, is still here. Build failed? Where? Look, 4 days ago package build fine: https://abf.openmandriva.org/build_lists/817072

look at file list:

- task-mate-1.24.1-1-omv4002.noarch.rpm 
- task-mate-1.24.1-1.src.rpm 
- **task-mate-minimal-1.24.1-1-omv4002.noarch.rpm**

as you can see build successfully and even mate-minimal is here.

Look at spec now: https://github.com/OpenMandrivaAssociation/task-mate/blob/master/task-mate.spec#L50

L 50 - %package minimal
so everything is ok, because "task-" is not basic package with source files etc. it is just meta-package to collect all needed dependency.

With nm applet, we currently do not issue Mate ISO, so I don't know if it bothers. By installing the environment from task-mate, we have the nm applet installed anyway, because it is included in the list from other environments.
Even other distros not include it in task-. But I think at some point, we can try include it, probably won't hurt.

Anyway, if we even ship Mate ISO (even as experiment, as few months ago), then nm applet should be pulled because is included on ISO. See here: https://github.com/OpenMandrivaAssociation/omdv-build-iso/blob/master/iso-pkg-lists-cooker/omdv-mate.lst#L46

**Comment by CasualRascal** [comment]
Interesting, ABF does not show that to me, also does not show me the successfully packaged x86_64 task-mate.
However I did this: install omlx41, switched to cooker unsupported, installed task-mate. task-mate-minimal was resolved and installed however after getting into mate the nm-applet was missing and had to manually install it. I thought maybe it would be better to put it in the package or add it as dependency for mate-panel.
Without the applet, connecting to internet must be done through cli and it's not a good experience

**Comment by AngryPenguinPL** [comment]
I added it. It should be ok. Like I said, it shouldn't hurt. By the way, I don't understand why your mate installation is missing a nm panel? Since it is installed by default from other environments. Last time I checked on clean install after installing mate, I had nm applet ... Strange but nvm, should be fixed now.
